steps:
- name: docker
  args: ['build', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
      - functions
      - deploy
      - HelloHTTP
      - '--source=./pkg/helloworld'
      - '--runtime'
      - 'go113'
      - '--trigger-http'
