openapi: "3.0.0"
info:
  title: "rest api for minecraft rcon"
  version: 0.1.0-alpha
paths:
  /players/:
    get:
      summary: lists all current players on the server
      responses:
        '200':
          description: successful list players request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/players'
  /saves/:
    post:
      summary: saves game state
      responses:
        '200':
          description: world was saved
          content:
            application/json:
              schema:
                $ref: ''
components:
  schemas:
    players:
      type: object
      properties:
        playerList:
          type: array
          items:
            type: string
    saveInfo:
      type:
        object:
