steps:
    -   name: mirror.gcr.io/library/golang
        env: ['GO111MODULE=on']
        args: ['go', 'build', './...']
    -   name: mirror.gcr.io/library/golang
        env: ['GO111MODULE=on']
        args: ['go', 'test', './...']
    -   name: mirror.gcr.io/library/golang
        env: ['GO111MODULE=on']
        args: ['golint', '-set_exit_status' ,'./...']
